version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Copenhagen
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      ngrx:
        patterns:
          - "@ngrx/*"
      testing-tooling:
        patterns:
          - "@types/*"
          - jasmine-core
          - karma*
          - typescript

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Copenhagen
    labels:
      - dependencies
      - github-actions
